
import type { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: 'eyeglasses',
    name: 'Eyeglasses',
    description: 'Frames that define your character.',
    imageId: 'category-eyeglasses',
  },
  {
    id: 'screen-glasses',
    name: 'Screen Glasses',
    description: 'Protect your eyes with our blue-light filtering lenses.',
    imageId: 'offer-banner-2',
  },
  {
    id: 'sunglasses',
    name: 'Sunglasses',
    description: 'Iconic shades for sunny days.',
    imageId: 'category-sunglasses',
  },
  {
    id: 'kids-glasses',
    name: 'Kids Glasses',
    description: 'Durable and fun frames for little ones.',
    imageId: 'category-kids',
  },
  {
    id: 'contact-lenses',
    name: 'Contact Lenses',
    description: 'Crystal clear vision, without the frames.',
    imageId: 'category-contacts',
  },
];

export const products: Product[] = [
  // Eyeglasses
  {
    id: '1',
    slug: 'the-classic-reader',
    name: 'The Classic Reader',
    category: 'eyeglasses',
    price: 129.99,
    description: 'A timeless design that combines sophistication with everyday comfort. Perfect for the modern professional.',
    imageId: 'product-1',
    images: ['product-1', 'product-2', 'product-9'],
    frameType: 'Full Frame',
    frameShape: 'Rectangle',
    gender: 'Unisex',
    frameSize: 'Medium',
  },
  {
    id: '2',
    slug: 'the-minimalist-frame',
    name: 'The Minimalist Frame',
    category: 'eyeglasses',
    price: 99.99,
    description: 'Sleek, lightweight, and effortlessly stylish. For those who believe less is more.',
    imageId: 'product-2',
    images: ['product-2', 'product-9', 'product-10'],
    frameType: 'Rimless',
    frameShape: 'Rectangle',
    gender: 'Unisex',
    frameSize: 'Narrow',
  },
  {
    id: '9',
    slug: 'the-scholar',
    name: 'The Scholar',
    category: 'eyeglasses',
    price: 149.99,
    description: 'Round frames for a touch of academic charm. Smart, stylish, and ready for any intellectual pursuit.',
    imageId: 'product-9',
    frameType: 'Full Frame',
    frameShape: 'Round',
    gender: 'Unisex',
    frameSize: 'Medium',
  },
  {
    id: '10',
    slug: 'the-ceo',
    name: 'The CEO',
    category: 'eyeglasses',
    price: 249.99,
    description: 'Command the room with these powerful, rimless frames. The ultimate statement of authority and style.',
    imageId: 'product-10',
    frameType: 'Rimless',
    frameShape: 'Geometric',
    gender: 'Men',
    frameSize: 'Wide',
  },
  
  // Screen Glasses
  {
    id: '13',
    slug: 'madrid-tortoise-shell',
    name: 'Madrid Tortoise Shell Square Eyeglasses',
    description: 'Premium Full-Rim Frames for Men & Women',
    price: 799,
    category: 'screen-glasses',
    imageId: 'product-13',
    frameType: 'Full Frame',
    frameShape: 'Square',
    gender: 'Unisex',
    frameSize: 'Medium',
  },
  {
    id: '14',
    slug: 'bold-oversized-tortoise-aviator',
    name: 'Bold Oversized Tortoise Shell Aviator Eyeglasses',
    description: 'Retro Square Fashion Frames for Men & Women',
    price: 899,
    category: 'screen-glasses',
    imageId: 'product-14',
    frameType: 'Full Frame',
    frameShape: 'Aviator',
    gender: 'Unisex',
    frameSize: 'Wide',
  },
  {
    id: '15',
    slug: 'oversized-retro-tortoise-italian',
    name: 'Oversized Retro Tortoise Shell Eyeglasses',
    description: 'Full-Rim Italian Design Fashion Frames for Men & Women',
    price: 999,
    category: 'screen-glasses',
    imageId: 'product-15',
    frameType: 'Full Frame',
    frameShape: 'Cat Eye',
    gender: 'Unisex',
    frameSize: 'Wide',
  },
  {
    id: '16',
    slug: 'transparent-grey-square',
    name: 'Transparent Grey Square Eyeglasses',
    description: 'Premium Lightweight Frame for Men & Women',
    price: 699,
    category: 'screen-glasses',
    imageId: 'product-16',
    frameType: 'Full Frame',
    frameShape: 'Square',
    gender: 'Unisex',
    frameSize: 'Medium',
  },
  {
    id: '17',
    slug: 'transparent-blue-square',
    name: 'Transparent Blue Square Eyeglass Frame',
    description: 'Unisex Lightweight Spectacles',
    price: 699,
    category: 'screen-glasses',
    imageId: 'product-17',
    frameType: 'Full Frame',
    frameShape: 'Square',
    gender: 'Unisex',
    frameSize: 'Medium',
  },

  // Sunglasses (placeholder - will be replaced by DB fetch)
  {
    id: '3',
    slug: 'the-aviator',
    name: 'The Aviator',
    category: 'sunglasses',
    price: 179.99,
    description: 'The iconic aviator, reimagined for the modern adventurer. Classic cool with superior UV protection.',
    imageId: 'product-3',
    frameType: 'Full Frame',
    frameShape: 'Aviator',
    gender: 'Unisex',
    frameSize: 'Wide',
  },
  {
    id: '4',
    slug: 'the-wayfarer',
    name: 'The Wayfarer',
    category: 'sunglasses',
    price: 159.99,
    description: 'An undisputed classic that never goes out of style. Versatile, comfortable, and always on-trend.',
    imageId: 'product-4',
    frameType: 'Full Frame',
    frameShape: 'Square',
    gender: 'Unisex',
    frameSize: 'Medium',
  },
  {
    id: '11',
    slug: 'sunset-shades',
    name: 'Sunset Shades',
    category: 'sunglasses',
    price: 139.99,
    description: 'Chic cat-eye sunglasses that bring a touch of vintage glamour to any outfit.',
    imageId: 'product-11',
    frameType: 'Full Frame',
    frameShape: 'Cat Eye',
    gender: 'Women',
    frameSize: 'Medium',
  },
  {
    id: '12',
    slug: 'ocean-drive',
    name: 'Ocean Drive',
    category: 'sunglasses',
    price: 199.99,
    description: 'Sporty and sleek, these sunglasses are built for action. Perfect for an active lifestyle.',
    imageId: 'product-12',
    frameType: 'Half Rim',
    frameShape: 'Rectangle',
    gender: 'Men',
    frameSize: 'Wide',

  },
  {
    id: '5',
    slug: 'the-explorer-kids',
    name: 'The Explorer',
    category: 'kids-glasses',
    price: 79.99,
    description: 'Durable and colorful frames designed to keep up with your child\'s biggest adventures.',
    imageId: 'product-5',
    frameType: 'Full Frame',
    frameShape: 'Square',
    gender: 'Kids',
    frameSize: 'Narrow',
  },
  {
    id: '6',
    slug: 'flexi-frames-kids',
    name: 'Flexi-Frames',
    category: 'kids-glasses',
    price: 89.99,
    description: 'Made from ultra-flexible material, these glasses can handle anything your kid throws at them.',
    imageId: 'product-6',
    frameType: 'Full Frame',
    frameShape: 'Round',
    gender: 'Kids',
    frameSize: 'Narrow',
  },
  {
    id: '7',
    slug: 'clarity-dailies',
    name: 'Clarity Dailies',
    category: 'contact-lenses',
    price: 49.99,
    description: '30-pack of daily disposable lenses for ultimate comfort and convenience.',
    imageId: 'product-7',
  },
  {
    id: '8',
    slug: 'vision-plus-monthlies',
    name: 'Vision Plus Monthlies',
    category: 'contact-lenses',
    price: 39.99,
    description: 'A single pair of monthly contact lenses, providing crisp vision all month long.',
    imageId: 'product-8'
  },
];
